# Generated by Django 4.2.7 on 2023-12-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptkokushi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
