# Generated by Django 4.2.7 on 2023-12-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptkokushi', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='name',
            new_name='age',
        ),
    ]
