# Generated by Django 4.2.7 on 2023-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptkokushi', '0006_delete_age_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.IntegerField()),
            ],
        ),
    ]
